// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCore.Models;

public partial class Language
{
    public int Id { get; set; }

    public string LocalName { get; set; }

    public string CultureName { get; set; }

    public string FriendlyName { get; set; }

    public bool Active { get; set; }

    public int DisplayOrder { get; set; }

    public virtual ICollection<AlbumLocalized> AlbumLocalizeds { get; } = new List<AlbumLocalized>();

    public virtual ICollection<BannerLocalized> BannerLocalizeds { get; } = new List<BannerLocalized>();

    public virtual ICollection<CareerLocalized> CareerLocalizeds { get; } = new List<CareerLocalized>();

    public virtual ICollection<CityLocalized> CityLocalizeds { get; } = new List<CityLocalized>();

    public virtual ICollection<FaqCategoryLocalized> FaqCategoryLocalizeds { get; } = new List<FaqCategoryLocalized>();

    public virtual ICollection<FaqLocalized> FaqLocalizeds { get; } = new List<FaqLocalized>();

    public virtual ICollection<HomeBannerLocalized> HomeBannerLocalizeds { get; } = new List<HomeBannerLocalized>();

    public virtual ICollection<InfoPageCategoryLocalized> InfoPageCategoryLocalizeds { get; } = new List<InfoPageCategoryLocalized>();

    public virtual ICollection<InfoPageLocalized> InfoPageLocalizeds { get; } = new List<InfoPageLocalized>();

    public virtual ICollection<MetaTagLocalized> MetaTagLocalizeds { get; } = new List<MetaTagLocalized>();

    public virtual ICollection<NewsLocalized> NewsLocalizeds { get; } = new List<NewsLocalized>();
}