// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCore.Models;

public partial class MetaTag
{
    public int Id { get; set; }

    public int PageId { get; set; }

    public string OpenGraphImage { get; set; }

    public virtual ICollection<MetaTagLocalized> MetaTagLocalizeds { get; } = new List<MetaTagLocalized>();

    public virtual SitePage Page { get; set; }
}