// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCore.Models;

public partial class SettingCategory
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Setting> Settings { get; } = new List<Setting>();
}