// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppCore.Models;

public partial class SitePage
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Banner> Banners { get; } = new List<Banner>();

    public virtual ICollection<MediaCollection> MediaCollections { get; } = new List<MediaCollection>();

    public virtual ICollection<MediaItem> MediaItems { get; } = new List<MediaItem>();

    public virtual ICollection<MetaTag> MetaTags { get; } = new List<MetaTag>();
}