//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicData.Admin.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SectionPhoto
    {
        public int Id { get; set; }
        public int SectionId { get; set; }
        public string Photo { get; set; }
    
        public virtual Section Section { get; set; }
    }
}
